name: Deploy Cloudflare Worker

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event.release.draft == true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'cloudflare-worker'
          wranglerVersion: '4'